name: S3-output

on: push

env:
  branch-name: ${GITHUB_REF#refs/heads/}
  bucket-name: 'dokka-snapshots'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dokka
      uses: actions/checkout@v2
      with:
        path: dokka

    - uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Publish dokka locally
      run: ./gradlew clean publishToMavenLocal --stacktrace
      working-directory: ./dokka

    - name: Checkout stdlib
      uses: actions/checkout@v2
      with:
        repository: 'kamildoleglo/kotlin-dokka-stdlib'
        ref: 'master'
        path: stdlib

    - name: Document stdlib
      run: ./gradlew clean callDokka --stacktrace
      working-directory: ./stdlib

    - name: Configure AWS credentials for S3 access
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Copy files to dokka's S3 bucket
      run: |
        aws s3 --recursive rm s3://${{ env.bucket-name }}/${{ env.branch-name }}/stdlib/prev
        aws s3 --recursive mv s3://${{ env.bucket-name }}/${{ env.branch-name }}/stdlib/latest s3://${{ env.bucket-name }}/${{ env.branch-name }}/stdlib/prev
        aws s3 sync ./stdlib/build/dokka s3://${{ env.bucket-name }}/${{ env.branch-name }}/stdlib/latest
